uid = nobody
gid = nogroup
use chroot = yes
max connections = 2
address = 192.168.11.11
# Note: If DNS lookup is slow, disable it with 2 items below:
reverse lookup = false
forward lookup = false
hosts allow = 192.168.11.0/24
pid file = /var/run/rsyncd.pid
log file = /var/log/rsyncd.log
# Note: A (real or non-existent) user without password is unavailable, even if it's root or has rw privilege.
secrets file = /etc/rsyncd.secrets

[lan_camera]
    path = /opt/lan_camera/save/server
    read only = yes
    auth users = lanc, foo:deny, orangepi:rw

